[package]
name = "ji-kids-bytes"
version = "0.1.0"
authors = ["dakom <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = {version = "^0.7", optional = true }
listenfd = {version = "^0.3", optional = true }
jsonwebtoken = "^7.1"
reqwest = { version = "^0.10", features = ["json"] }
tokio = { version = "^0.2", features = ["full"] }
warp = "^0.2"
cfg-if = "^0.1"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_derive = "^1.0"
strum = "^0.18"
strum_macros = "^0.18"
dotenv = "^0.15"
lazy_static = "^1.4"
log = "^0.4"
futures-util = "0.3.4"
handlebars = "3.0.1"
chrono = "0.4.11"

# TODO
# ji_cloud_shared = {path = "../ji-cloud/ji-cloud-shared/rust", features=["frontend"]}
ji_cloud_shared = {version = "0.1.0", features = ["frontend"]}

[features]
local = ["simplelog", "listenfd"]
quiet = []
local-quiet = ["local", "quiet"]
release = []
