###################
## Dev           ##
###################

[tasks.dev]
run_task = [{name = [
    "local-quiet",
]}]


###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
DOCKER_BUILDKIT = "1"

###################
## Gcloud        ##
###################

[tasks.gcloud-configure-docker]
script_runner = "@shell"
script = ["gcloud auth configure-docker"]

###############################
## Local (with autoreload)    #
## see server.rs              #
###############################
[tasks.local]
run_task = { name = [ "node-local", "server-local", ], parallel = true }

[tasks.local-quiet]
run_task = { name = [ "node-local", "server-local-quiet", ], parallel = true }

[tasks.node-local]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = ["npm start"]

[tasks.server-local]
command = "systemfd"
args = ["--no-pid", "-s", "http::8081", "--", "cargo", "watch", "-w", "../ji-cloud/ji-cloud-shared/rust", "-w", ".", "-x", "run --features local"]

[tasks.server-local-quiet]
command = "systemfd"
args = ["--no-pid", "-s", "http::8081", "--", "cargo", "watch", "-w", "../ji-cloud/ji-cloud-shared/rust", "-w", ".", "-x", "run --features local-quiet"]


###################
## Release       ##
###################

[tasks.release]
run_task = [{name = [
    "gcloud-configure-docker",
    "node-release",
    "docker-build-release",
    "docker-publish-release",
    "gcloud-deploy-release",
]}]

[tasks.node-release]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = ["npm run build"]

[tasks.docker-build-release]
command = "docker"
args = ["build", "--target", "release", "-t", "gcr.io/ji-kids/ji-kids-bytes:latest", "."]

[tasks.docker-publish-release]
command = "docker"
args = ["push", "gcr.io/ji-kids/ji-kids-bytes:latest"]

[tasks.gcloud-deploy-release]
script_runner = "@shell"
script = ["gcloud run deploy ji-kids-bytes --project ji-kids --region europe-west1 --image gcr.io/ji-kids/ji-kids-bytes:latest --platform managed"]